# Generated by Django 4.2.6 on 2024-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field2', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field3', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field4', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field5', models.CharField(blank=True, default='unset', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Table1-data',
                'verbose_name_plural': 'Table1',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field2', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field3', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field4', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field5', models.CharField(blank=True, default='unset', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Table2-data',
                'verbose_name_plural': 'Table2',
            },
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field2', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field3', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field4', models.CharField(blank=True, default='unset', max_length=50, null=True)),
                ('field5', models.CharField(blank=True, default='unset', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Table3-data',
                'verbose_name_plural': 'Table3',
            },
        ),
    ]
